services:
  mysql:
    image: mysql:8.4
    # quando cair ira reiniciar
    restart: always
    container_name: mysql-nlw
    # precisa da variavel de ambiente de senha
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    # porta padrao
    ports: 
      - '3336:3306'
    networks: 
      - nlw-network
networks:
  nlw-network:
    # quando crio um container eh criado uma rede propria - bridge cria uma ponte entre a rede do SO e o do container
    driver: bridge